### ISSUE TITLE
Is there any document about the repository?

### ISSUE THREAD

**Issue by mrayur** [emunaran/stochastic-human-driving-policies-drl#3]
Hi Emunaran,

Is there any document such as ppt or pdf about the repository?

Best,
John

**Comment by emunaran** [comment]
Hi John,
Thank you for your interest in this project. I'll soon add a README file.

Best,
Ran

**Comment by emunaran** [comment]
Hi John,
Please let me know if everything works for you and if I can close the issue.
Best,
Ran
